spring.application.name=UAV-Docking-Management-System
spring.datasource.url=jdbc:mysql://localhost:3305/uav_management_system
spring.datasource.username=root
spring.datasource.password=younes123
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect



